---
- hosts: all
 
  gather_facts: False
  become: True
  tasks:
  - name: comm1
    raw: df -kh
    register: sh_ip_int_br_result
  - name: comm2
    debug:
      msg: var is {{ sh_ip_int_br_result }}.
